### ISSUE TITLE
Second USB port

### ISSUE THREAD

**Issue by diogo-ivo** [ChocolateLoverRaj/gsc-debug-board#2]
Are there any plans for a board with two USB-C ports, one for serial access and the other wired to the USB D+/D- pins? This would allow for much easier debugging with devices with only one USB-C port since you don't have to plug the adapter in and out all the time.

**Comment by ChocolateLoverRaj** [comment]
Do you mean being able to connect a peripheral to the Chromebook such as a mouse or SSD and debugging the GSC through the same USB-C port?

1. I'm not sure if it's possible to connect USB devices to the same port while connecting to the GSC.
2. Why not use a USB hub? As far as I know all chromebooks have at least 2 USB ports (counting USB-C ports + USB-A ports)

**Comment by diogo-ivo** [comment]
No, I mean wiring up the A6/A7 pins to another USB-C connector so that the regular USB interface is exposed through there. This is useful on the Pixel C that has CCD but only 1 USB-C connector. I have a home-made cable that does this and it works but would like a more robust solution since the cables keep breaking when in transport

**Comment by ChocolateLoverRaj** [comment]
So does using peripherals such as a mouse and external storage through A6 and A7 work while the A5,B5,A8,B8 pins are used for CCD?

**Comment by diogo-ivo** [comment]
I have been using the A6/A7 connection for booting kernels from fastboot and with the cable I have I have no way of plugging in peripherals at the same time as using CCD but I would assume so since the A6/A7 pins are independent of the SBU1/SBU2 connection. At any rate even if it does not work just having the fastboot flashing + CCD in the same cable would be great!

**Comment by ChocolateLoverRaj** [comment]
So do you want to connect the A6,A7,VCC, and GND pins to a USB-C port and then use a USB-C cable to connect the 2nd port to your other computer? I will try it out. How can I test if it's working? Will an additional USB device show up with lsusb?

**Comment by diogo-ivo** [comment]
Yes, exactly. I don't know if the devices you own have fastboot or any similar modes (where the port works in a device role), but on the Pixel C when I go into fastboot it shows up in lsusb as another device. If your devices are all host mode then I guess you could try connecting some peripheral and see if anything happens :). Anyway, thank you for testing it!

**Comment by diogo-ivo** [comment]
Let me know if you need anything from me, I'll be happy to help

**Comment by ChocolateLoverRaj** [comment]
> when I go into fastboot it shows up in lsusb

Wdym by go into fastboot? Is there some command I should run before lsusb?

Also, the Chromebooks I have are robo360 and jinlon. I'm not sure if it will work for them.

**Comment by ChocolateLoverRaj** [comment]
Are these the only Chromebooks that will work with the second USB interface: https://www.chromium.org/chromium-os/chrome-os-systems-supporting-adb-debugging-over-usb/ ?

**Comment by diogo-ivo** [comment]
The fastboot part is a bootloader mode that you reach via a specific hardware button combination, so no command needed. I think it is exclusive to Android devices (the Pixel C has it because it was meant to be a Chromebook at some point but the plans were scrapped, hence also the presence of CCD), so neither of your devices should have it. As for the link you sent I think that is a good guess, maybe more support it but who knows. You could always try to plug in a regular USB stick or some other peripheral to the second USB-C port and see what happens on your devices

**Comment by ChocolateLoverRaj** [comment]
I found out from @WeirdTreeThing that it is possible to have a 2nd USB port and most Chromebooks will be a USB host for the 2nd USB port. However I will not be designing a PCB with an additional USB port because I think it is a very niche thing that 99% of people don't need. But FYI it is possible.

**Comment by itspolly** [comment]
so this board doesn't support USB + serial at the same time? looking for the same use case as this user: want to run `fastboot boot <img path>` and get UART/serial logs of boot output. does the board hookup the USB 3 data pins? or is it literally just SBU1/2 -> D+/-?

**Comment by WeirdTreeThing** [comment]
Well it's not like you can use this board for pixel phones without extra hardware anyway. But yeah, it just connects DUT SBU to host D+/-

**Comment by ChocolateLoverRaj** [comment]
I'm thinking of making a PCB that does expose both D+/D- and the SBU USB device with a built-in USB Hub. I have some questions:
- Besides Pixel phones and Google Pixel C is this useful for any other device?
- Would this cause any issues with most Chromebooks?
- What is the max USB speed of the regular (`fastboot`) USB device while serial through SBU is enabled? Is it 12Mbps? 480Mbps? Can it also use additional pins for USB >2.0, TX1/2 +/-?

**Comment by itspolly** [comment]
> Well it's not like you can use this board for pixel phones without extra hardware anyway. But yeah, it just connects DUT SBU to host D+/-

have you tried it? i ordered one because my USB cereal which is confirmed working with pixel phones isn’t gonna arrive for two weeks: was hoping this dongle would work with my pixel.

**Comment by ChocolateLoverRaj** [comment]
usb-cereal is different, it uses actual UART TX/RX and a UART to USB converter while you can use a SuzyQ on some Pixel phones which exposes a second D+/D- so a UART to USB converter isn't needed.

**Comment by WeirdTreeThing** [comment]
SuzyQ only works on pixels 3-5 and you only get access to a very limited gsc console on the titan m. For AP UART (along with UART for the various co-processors), you need cereal. You can take a SuzyQ and connect D+/D- from the host end to a usb UART converter and that will work as long as you have the proper voltage converter in between.

**Comment by itspolly** [comment]
my findings coincide with what WeirdTreeThing said: no AP UART on the pixel 8a and it's not even showing as a USB device. i've tried taking a SuzyQ and connecting D+/D- to a USB UART converter and no luck there either. Seems like the best option is a USB cereal, which I will have to wait for. Thank you for your help everyone!

**Comment by WeirdTreeThing** [comment]
You need to first run `fastboot oem uart enable` to enable AP UART. There are other UART commands you can explore as well.
